# -*- coding: utf-8 -*-
"""FODS LAB (21-23).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEsngkgz3YpuDBXYxEAKUz2HIFBP0OxU
"""

# ============================================================
# SCENARIO 21: ESTIMATION OF RARE ELEMENT CONCENTRATION
# ============================================================

import numpy as np
import pandas as pd
from google.colab import files

print("Upload the CSV file containing rare element measurements.")
uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Read CSV
data = pd.read_csv(filename)

print("\nColumns available in the dataset:")
print(list(data.columns))

# Use the first numeric column automatically
numeric_columns = data.select_dtypes(include=np.number).columns

if len(numeric_columns) == 0:
    raise ValueError("No numeric column was found in the CSV file.")

column = numeric_columns[0]
measurements = data[column].dropna().to_numpy()

print(f"\nUsing measurement column: {column}")
print(f"Total valid measurements: {len(measurements)}")

# ------------------------------------------------------------
# User inputs
# ------------------------------------------------------------

sample_size = int(input("\nEnter sample size: "))
confidence_level = float(input("Enter confidence level (e.g., 95 for 95%): "))
precision = float(input("Enter desired precision / maximum margin of error: "))

if sample_size <= 1:
    raise ValueError("Sample size must be greater than 1.")

if sample_size > len(measurements):
    raise ValueError("Sample size cannot exceed the number of available measurements.")

if not 0 < confidence_level < 100:
    raise ValueError("Confidence level must be between 0 and 100.")

if precision <= 0:
    raise ValueError("Precision must be greater than 0.")

# ------------------------------------------------------------
# Random sampling
# ------------------------------------------------------------

np.random.seed(42)

sample = np.random.choice(
    measurements,
    size=sample_size,
    replace=False
)

# ------------------------------------------------------------
# Calculate statistics
# ------------------------------------------------------------

sample_mean = np.mean(sample)
sample_std = np.std(sample, ddof=1)
standard_error = sample_std / np.sqrt(sample_size)

# Convert confidence level to z critical value.
# NumPy is used for the numerical calculations.
# For a normal approximation, common confidence levels are handled here.

z_values = {
    90: 1.645,
    95: 1.960,
    99: 2.576
}

if confidence_level in z_values:
    z_critical = z_values[confidence_level]
else:
    # Approximation using inverse error function
    # for arbitrary confidence levels
    from statistics import NormalDist
    z_critical = NormalDist().inv_cdf(
        1 - (1 - confidence_level / 100) / 2
    )

margin_of_error = z_critical * standard_error

lower_limit = sample_mean - margin_of_error
upper_limit = sample_mean + margin_of_error

# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("RARE ELEMENT CONCENTRATION ANALYSIS")
print("=" * 55)

print(f"Sample size             : {sample_size}")
print(f"Confidence level        : {confidence_level}%")
print(f"Sample mean             : {sample_mean:.6f}")
print(f"Sample standard deviation: {sample_std:.6f}")
print(f"Standard error          : {standard_error:.6f}")
print(f"Margin of error         : {margin_of_error:.6f}")

print(
    f"\n{confidence_level}% Confidence Interval:"
)
print(f"({lower_limit:.6f}, {upper_limit:.6f})")

print(f"\nDesired precision       : ±{precision:.6f}")

if margin_of_error <= precision:
    print("Result: REQUIRED PRECISION ACHIEVED")
else:
    print("Result: REQUIRED PRECISION NOT ACHIEVED")
    print("Consider increasing the sample size.")

print("=" * 55)

# ============================================================
# SCENARIO 22: CUSTOMER REVIEW CONFIDENCE INTERVAL
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats
from google.colab import files

print("Upload customer_reviews.csv")
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read CSV
df = pd.read_csv(filename)

print("\nAvailable columns:")
print(list(df.columns))

# Find numeric columns
numeric_columns = df.select_dtypes(include=np.number).columns

if len(numeric_columns) == 0:
    raise ValueError("No numeric rating column was found.")

# Automatically select the first numeric column
rating_column = numeric_columns[0]

ratings = df[rating_column].dropna()

if len(ratings) < 2:
    raise ValueError("At least two valid ratings are required.")

print(f"\nRating column used: {rating_column}")
print(f"Number of ratings: {len(ratings)}")

# ------------------------------------------------------------
# User input
# ------------------------------------------------------------

confidence_level = float(
    input("\nEnter confidence level (e.g., 95 for 95%): ")
)

if not 0 < confidence_level < 100:
    raise ValueError("Confidence level must be between 0 and 100.")

# ------------------------------------------------------------
# Statistics
# ------------------------------------------------------------

n = len(ratings)
mean_rating = ratings.mean()
std_rating = ratings.std()
standard_error = std_rating / np.sqrt(n)

alpha = 1 - confidence_level / 100

# t critical value
t_critical = stats.t.ppf(
    1 - alpha / 2,
    df=n - 1
)

margin_of_error = t_critical * standard_error

lower_bound = mean_rating - margin_of_error
upper_bound = mean_rating + margin_of_error

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("CUSTOMER REVIEW ANALYSIS")
print("=" * 55)

print(f"Number of ratings       : {n}")
print(f"Mean rating             : {mean_rating:.4f}")
print(f"Standard deviation      : {std_rating:.4f}")
print(f"Standard error          : {standard_error:.4f}")
print(f"Confidence level        : {confidence_level}%")
print(f"Margin of error         : {margin_of_error:.4f}")

print(
    f"\n{confidence_level}% Confidence Interval:"
)
print(f"Lower bound             : {lower_bound:.4f}")
print(f"Upper bound             : {upper_bound:.4f}")

print(
    f"\nWe are {confidence_level}% confident that "
    f"the true population mean rating lies between "
    f"{lower_bound:.4f} and {upper_bound:.4f}."
)

print("=" * 55)

# ============================================================
# SCENARIO 23: CLINICAL TRIAL HYPOTHESIS TEST
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

print("=" * 60)
print("CLINICAL TRIAL HYPOTHESIS TEST")
print("=" * 60)

# ------------------------------------------------------------
# Enter data
# ------------------------------------------------------------

control_input = input(
    "\nEnter control/placebo group values separated by commas:\n"
)

treatment_input = input(
    "\nEnter treatment group values separated by commas:\n"
)

# Convert input into NumPy arrays
control = np.array(
    [float(x.strip()) for x in control_input.split(",")]
)

treatment = np.array(
    [float(x.strip()) for x in treatment_input.split(",")]
)

# Check data
if len(control) < 2 or len(treatment) < 2:
    raise ValueError(
        "Both groups must contain at least two observations."
    )

# ------------------------------------------------------------
# Calculate descriptive statistics
# ------------------------------------------------------------

control_mean = np.mean(control)
treatment_mean = np.mean(treatment)

control_std = np.std(control, ddof=1)
treatment_std = np.std(treatment, ddof=1)

# ------------------------------------------------------------
# Hypothesis test
# ------------------------------------------------------------

# H0: The treatment has no effect.
# H1: The treatment has an effect.

t_statistic, p_value = stats.ttest_ind(
    treatment,
    control,
    equal_var=False
)

alpha = 0.05

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("RESULTS")
print("=" * 60)

print(f"Control group size       : {len(control)}")
print(f"Treatment group size     : {len(treatment)}")

print(f"\nControl mean             : {control_mean:.4f}")
print(f"Treatment mean           : {treatment_mean:.4f}")

print(f"\nControl standard deviation   : {control_std:.4f}")
print(f"Treatment standard deviation : {treatment_std:.4f}")

print(f"\nT-statistic              : {t_statistic:.4f}")
print(f"P-value                  : {p_value:.6f}")
print(f"Significance level       : {alpha}")

# ------------------------------------------------------------
# Decision
# ------------------------------------------------------------

print("\n" + "-" * 60)

if p_value < alpha:
    print("Decision: REJECT the null hypothesis (H0).")
    print(
        "Conclusion: The treatment has a statistically "
        "significant effect compared with the placebo."
    )
else:
    print("Decision: FAIL TO REJECT the null hypothesis (H0).")
    print(
        "Conclusion: There is not enough statistical evidence "
        "to conclude that the treatment has a significant effect."
    )

print("=" * 60)

# ------------------------------------------------------------
# Visualization
# ------------------------------------------------------------

plt.figure(figsize=(9, 6))

plt.boxplot(
    [control, treatment],
    labels=["Control / Placebo", "Treatment"]
)

plt.ylabel("Measurement")
plt.title("Clinical Trial: Control vs Treatment")

plt.grid(axis="y", alpha=0.3)

plt.show()

# ------------------------------------------------------------
# Mean comparison graph
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

groups = ["Control / Placebo", "Treatment"]
means = [control_mean, treatment_mean]

plt.bar(groups, means)

plt.ylabel("Mean Measurement")
plt.title("Mean Comparison: Control vs Treatment")

plt.show()
